image: docker.gamechanger.io/test/deferrable
git:
  depth: 10
env:
  - REPO=/var/cache/drone/src/github.com/gamechanger/deferrable
services:
  - redis
script:
  - cd $REPO
  - pip install -q .
  - |
    python -c "import dynamic_requirements; f = open('requirements.txt', 'w'); map(lambda x: f.write(x + '\n'), dynamic_requirements.test_requires)"
  - pip install -q -r requirements.txt
  - nosetests
  - tests_complete deferrable
notify:
  webhook:
    urls:
      - http://localhost:7777/webhook
    on_success: true
    on_failure: true
