image: docker.gamechanger.io/test/deferrable
git:
  depth: 10
env:
  - REPO=/var/cache/drone/src/github.com/gamechanger/deferrable
services:
  - redis
script:
  - cd $REPO
  - python setup.py test
  - tests_complete deferrable
notify:
  webhook:
    urls:
      - http://localhost:7777/webhook
    on_success: true
    on_failure: true
