version: '3.7'
networks:
  tests:
    name: tests
services:
  redis:
    hostname: redis
    image: redis:2.8
    networks:
    - tests
  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    init: true
    volumes:
      - .:${MOUNT_PATH:-/mnt/test}
    depends_on:
    - redis
    environment:
      GIT_BRANCH: ${CI_COMMIT_REF_NAME:-master}
    command: make install test
    networks:
    - tests
    working_dir: /mnt/test
